### ISSUE TITLE
Documentation and test for `predict.py`

### ISSUE THREAD

**Issue by glatard** [big-data-lab-team/repro-tools#56] opened 2017-10-12 14:55 UTC
* Update README.md in base directory to explain that there are now two tools.
* Give a brief (1 or 2 sentences) explanation on `predict.py`.
* Add test data to the repo and add a test to `predict.py`.

**Comment by ali4006** [comment] 2020-05-18 05:26
Duplicate of #83

**Closed as completed** 2020-05-25 19:02 UTC
Labels: enhancement
